apiVersion: v1
kind: Service
metadata:
  name: my-bluegreen-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: myapp
    version: blue  # This targets the blue deployment