apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-nginx-pod
  name: my-nginx-pod
  namespace: default
spec:
  containers:
  - name: my-nginx-pod
    image: nginx:stable
    ports:
      - containerPort: 80
    env:
      - name: USER
        value: "username"
    imagePullPolicy: IfNotPresent

