apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      name: busybox-pod
  template:
    metadata:
      labels:
        name: busybox-pod
    spec:
      containers:
        - command:
            - sh
            - -c
            - echo Hello Kubernetes! && sleep 3600
          image: busybox888
          imagePullPolicy: Always
          name: busybox-container