apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app-v1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
      version: v1
  template:
    metadata:
      labels:
        app: my-app
        version: v1
    spec:
      containers:
        - name: myapp
          image: monik/blue-version:1.0.0
          ports:
            - containerPort: 80