apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: v2
  template:
    metadata:
      labels:
        app: my-app
        version: v2
    spec:
      containers:
        - name: myapp
          image: monik/green-version:2.0.0
          ports:
            - containerPort: 80